### ISSUE TITLE
Email verification - Investor onboarding flow integration (v1)

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1094]
[Specs](https://centrifuge.hackmd.io/2QRq1sl7RSKd2AB0RVbp1w)
## Background
Every Investor will verify their email and each wallet will be tied to one email address.

## Acceptance Criteria
* set up email template in Sendgrid
* send email that includes a valid confirmation link that redirects to onboarding flow
* Tooltip: "Your email will be verified. Please make sure you have access to confirm."
*  add notifications on next page 

<img width="897" alt="Screenshot 2022-11-30 at 12 46 34" src="https://user-images.githubusercontent.com/31280003/204799120-dc2c91bd-895d-4804-8d80-8d7143727d81.png">

**Comment by sophialittlejohn** [comment]
@annamehr I think we should add an email field to the authorized signer verification for the user if not a business user. Otherwise we cannot capture every users email address.

<img width="730" alt="Screenshot 2023-01-30 at 10 40 43" src="https://user-images.githubusercontent.com/24418964/215523115-78ffe497-52b0-40bc-890b-31456ae60ae3.png">

Also, at which step in the entity and individual flows should the email verification be completed? In other words, how far can the user get before having verifying their email?
