### ISSUE TITLE
Unsupported Browser error 

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#1447]
* Display a warning message if an unsupported browser is used to users in Firefox and Safari.
* Text: `Change or update your browser for a fully supported experience. Centrifuge App fully support Chromium web browsers (Brave, Opera or Google Chrome). `
* We depend on EVM (Metamask, Wallet connect) and Substrate wallets (Talisman, Polkadot.js) which are not stable in Firefox and Safari.
* Most of the UI is only tested on Chrome/Brave so even for FireFox it is probably safer to remind users that they should probably be opening the page in Chrome.

**Comment by TimHoub** [comment]
What is the reason of it not working on Safari? At the moment it shows nothing.

We should explore if we can at least show the app, statistics etc but with a message that because of 'x' reasons Chrome is preferred to invest and withdraw and get the full experience.
If I was a user and visit to the app using Safari. -> Got a message that it is not supported. Chances are high that I might just leave the app for what it is and go to another one.

I need to be very convinced of using Centrifuge already to switch browsers.

**Comment by TimHoub** [comment]
It might not be a big issue as I was looking into browsers stats and chrome makes up 80%, Edge 10%, Firefox 5%, Safari 3% and then some others like brave, opera. 

Do we have any browser stats for centrifuge website/ App?

**Comment by sophialittlejohn** [comment]
Here are some stats from cloudflare on browser usage (just over the last week)

<img width="416" alt="Screenshot 2023-08-01 at 12 42 06" src="https://github.com/centrifuge/apps/assets/24418964/4799aca2-7ca0-4702-83c2-9e7838a4b78e">
