### ISSUE TITLE
Polkadot vault transaction error

### ISSUE THREAD

**Issue by annamehr** [centrifuge/apps#1608]
**High priority bug**

**Bug report**
* Unable to sign txns with Polkadot vault 
* I tried using both talisman and Polkadot.js extension
* Web3Foundation and Jay have tried

**Steps to Reproduce**
* Connect Polkadot Vault with Talisman
* Connect Talisman wallet and Centrifuge app
* Start onboarding and sign transaction

![unnamed-1](https://github.com/centrifuge/apps/assets/31280003/8e66f1d2-9fe6-4087-8ba0-ad9c6534538b)
![image](https://github.com/centrifuge/apps/assets/31280003/8a647314-b235-4706-94dc-0d952f28191c)
![image (1)](https://github.com/centrifuge/apps/assets/31280003/fb7f3c47-6723-486f-9c9c-fae1c655378f)
![image (2)](https://github.com/centrifuge/apps/assets/31280003/9415a6f9-9f4e-457b-9ee1-2f85cee00ee5)

**Comment by jpangelle** [comment]
After digging in, I don't think this is an issue on the app side.

If I just try to sign a "raw" transaction directly from the Polkadot portal using Talisman with a Polkadot Vault account, I get the same error:

### Transaction

<img width="689" alt="image" src="https://github.com/centrifuge/apps/assets/28536523/6bfe4ad6-4013-4d16-b6ef-41304ebb6b3d">

### Result

![image](https://github.com/centrifuge/apps/assets/28536523/75da7cf0-3f27-459e-875f-58cacfa08465)

For polkadot.js, same thing:

### Transaction and Result
<img width="1091" alt="image" src="https://github.com/centrifuge/apps/assets/28536523/a16bda74-b48f-4b0a-a902-5670615d5b9a">

I found this [Github issue](https://github.com/polkadot-js/extension/pull/1155) which supposedly fixed the issue. This issue was closed in October 2022 but [Polkadot.js extension](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd) has not been updated since June 2022 so the fix is not reflected in the extension so that explains the issue with Polkadot.js.

For Talisman, I found this statement in an open [issue](https://github.com/TalismanSociety/talisman/issues/924#issuecomment-1635198266):

> Currently Talisman inherits its signing logic directly from the polkadot.js extension. So, if polkadot.js can sign something, we should be able to too, and if we can't but they can, we would consider it a bug.

So ultimately, I think the the polkadot.js folks need to release a new version/extension and this will resolve both the polkadot.js extension and Talisman issue.

It appears that there is an [open to do](https://github.com/polkadot-js/extension/issues/1283) for this in the polkadot.js extension repo with activity as recently as August 29 so they appear to be working on it. Until this is done, I don't think there is anything we can do on our end.
