### ISSUE TITLE
Sticky reporting header and first column

### ISSUE THREAD

**Issue by hieronx** [centrifuge/apps#2228]
On the Reporting tab, if you scroll down, the header should be sticky. See screenshot below for the sticky part:
<img width="1800" alt="Screenshot 2024-06-19 at 19 01 18" src="https://github.com/centrifuge/apps/assets/1748621/2fc96c59-aca3-4d16-8f09-017278e35282">

Also, if you scroll right within the table, the first column should be sticky.

**Comment by kattylucy** [comment]
This a bit more complicated that it seems - every square on the picture is a different component making it a bit difficult to make the whole thing sticky. The best solution would only have the filters to be sticky (red square on picture) otherwise we will have to change the entire layout to make it work. 

Another question is, do we want the header to be sticky as well? (blue square on screenshot)

How do we want to tackle this? Im up for either solution but want to get some feedback.

@hieronx @sophialittlejohn 

![Image](https://github.com/centrifuge/apps/assets/51223655/fa3b8c16-c4c8-438f-a78c-3ce4a69e30f5)

**Comment by hieronx** [comment]
@kattylucy what is most important to have sticky, is actually the table header, as in the row with the dates here. Everything above that is optionally sticky, not as important. Ideally I would say the blue section from my initial section is sticky, so everything excluding the header.

**Comment by sonam-jo** [comment]
Will be addressing in with the Reporting tab revamp
