### ISSUE TITLE
Fix 404 loading asset detail in Legacy Tinlake

### ISSUE THREAD

**Issue by sophialittlejohn** [centrifuge/apps#2236]
From bug report: 
> Databased finance can not access their final asset in order to repay. Once its repaid we need to write down the rest of the asset (100%) so the final tin investor can collect the DAI and the pool can be closed.

> The asset page in [tinlake](https://legacy.tinlake.centrifuge.io/pool/databased-finance-1/assets)  wont load. I cant access it using the old trick of adding /asset?assetId=57 to the end of the link. Any idea how we can help the issuer repay through the UI in order to close out this pool?

**Comment by AStox** [comment]
I investigated a bit. I think the issue has something to do with the fact that normally `http://localhost:3000/pool/0xfc2950dd337ca8496c18dfc0256fb905a7e7e5c6/databased-finance-1/assets/asset?assetId=57` would render a page, but clicking on any archived pool routes you to `http://localhost:3000/pool/[slug]` instead of `http://localhost:3000/pool/[root]/[slug]`. Then anything after `http://localhost:3000/pool/[slug]` like `http://localhost:3000/pool/[slug]/assets/asset?assetId=57` returns a 404 since it's not matching the path structure anymore.

Oddly trying to visit `http://localhost:3000/pool/[root]/[slug]/assets/asset?assetId=57` directly, with the [root] included still yields a 404, even though as far as I can tell that IS matching the correct path structure.
