### ISSUE TITLE
INVESTIGATE: Asset 110 in CF4 not showing up in asset list

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#257]
See here: https://tinlake.centrifuge.io/pool/0xdb3bc9fb1893222d266762e9ff857eb74d75c7d6/consolfreight-4/assets/asset?assetId=110
This asset is not in the list. Bit more background and tx links here: https://centrifugehq.slack.com/archives/C01CM3L2V7H/p1624271639003200

Seems to be specific to CF4, CFG rewards plus other pools seem to work fine

**Comment by jpangelle** [comment]
It looks like the response from the graph is first 100 items by default. This is probably only happening to CF4 because it is the only pool with 100+ assets.

The `subgraph` query is here: https://github.com/centrifuge/apps/blob/main/tinlake-ui/services/apollo/index.ts#L253-L298

By default, it is returning the first 200. However, if you edit the query to below, it returns the proper amount:

```
gql`{
  pools (where : {id: "${root.toLowerCase()}"}){
    id
    loans (first: 200) { // <-------------
      id
      pool {
        id
      }
      index
      owner
      opened
      closed
      debt
      interestRatePerSecond
      ceiling
      threshold
      borrowsCount
      borrowsAggregatedAmount
      repaysCount
      repaysAggregatedAmount
      nftId
      nftRegistry
      maturityDate
      financingDate
    }
  }
}
`
```

**Comment by denniswell** [comment]
Already, can we turn INVESTIGE into FIX ;-)? Feels like a relatively simple fix? And should probably be rolled out for all pools?
