### ISSUE TITLE
Add average values to portfolio distribution

### ISSUE THREAD

**Issue by denniswell** [centrifuge/apps#588]
On the pool asset tab we currently show a "Portfolio distribution" component. It would be helpful if also show avg financing fee and in particular avg risk ajdustment (needed for valuation) as a header row. In the same row we can then also show 100% as total of portfolio distribution

Avg financing fee = Average of financing fees weighted by share of portfolio (we already have it on Pool overview page, should eual this number

Avg Risj adjustment = Weighted by share of portfolio

Mockup:
![image](https://user-images.githubusercontent.com/23652850/155942794-bd04b9a1-9d59-4c2e-ac7c-8106c44f272c.png)

[Figma link](https://www.figma.com/file/EWziKt1qCFdHGhWdnkrcKf/Tinlake-UI?node-id=8623%3A29321)

**Comment by alessioscalici** [comment]
@denniswell @armandomistral is there already a mockup for this task?

**Comment by armandomistral** [comment]
@alessioscalici, here's the current mockup of the Pool's Asset tab: https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=1171%3A20906. @denniswell, can you provide please more background about WHY this change is needed, WHAT's the problem (so I can assess whether the suggested header row is the adequate solution)

**Comment by armandomistral** [comment]
> as described the avg risk ajdustment is needed for valuation settings
…do you mean the valuation of the portfolio? Which number expresses the valuation of a portfolio?

I propose to add `Average financing fee` and `Average risk adjustment` in th header of the expandable, the same way it's done on the Maker integration expandable card. I don't think showing the 100% would make sense there, as it's not a row of the table. I'm also wondering whether the Portfolio distribution card should be moved ABOVE the asset list, since in most cases it's below the fold and therefore hard to reach.
![image](https://user-images.githubusercontent.com/23652850/155678893-89aadb4d-286d-454e-bd7a-869b136ed2b7.png)

**Comment by denniswell** [comment]
Yeah, fine to move above the asset list
