### ISSUE TITLE
List of Pools - Public Pools list  - MVP v1

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#705]
Any user can view the list of live pools

### List of Pools
[Spec](https://centrifuge.hackmd.io/K2KYOmgASMqW---8helRWA#List-of-Pools)

When a pool is selected the user redirects to the pool details page
- Show list of live pools
    - Displaying their Name, Icon and Asset class
- Value
    - This is the current pool value
    - The list can be sorted by Value (most to leave value and visa versa)

**Comment by armandomistral** [comment]
@EstherCentrifuge, I reopened this issue, because the implementation on https://demo.app.cntrfg.com/pools does not show the icon (AKA pool thumbnail) See  ![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/4d468f9d-3f6d-4b36-a82f-c894378d480a)

### Target
Show pool icon in first column of pool list
[Spec](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=6203%3A33801)
