### ISSUE TITLE
Issuer details - Token details - Altair

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#771]
[Specs](https://centrifuge.hackmd.io/m4QFRZzoQs-h7P7qcMzC_w#Issuer-details)
[Figma](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=3220%3A73527)
- Name, logo and description
The issuer name, logo and description are mandatory for each pool and set during [creation and can be updated in manage pool](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA?both#Issuer-details)
- links
All links are set during the [pool creation or in the manage pool options](https://centrifuge.hackmd.io/1OiMlCCWTL2YwUN8c_sFnA?both#links)
    - When a link is selected the user can go to the URL (website, forum) or start an email in their default email progrem (contact/email)
    - The Executive summary links opens a [overlay to prompt confirmation on viewing the executive Summary](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app?node-id=3101%3A71772). Once confirmed a PDF download starts.
        * Title: `Confirmation required`
        * Modal description: `By clicking the button below, you confirm that you are requesting the executive summary without having been solicited or approached, directly or indirectly by the issuer of New Silver 2 or any affiliate. `

**Comment by sophialittlejohn** [comment]
@EstherCentrifuge a few calculation questions again:
1. `Pool Value`: is it correct to assume `totalReserve + latestNav` ?
2. What does `Age` refer to? Maybe the current epoch?
3. `Average asset maturity`: where does this number come from or how can it be calculated?

**Comment by sophialittlejohn** [comment]
From @offerijns:

> 1. Pool Value: is it correct to assume totalReserve + latestNav ?

Yep this is correct

> 2. What does Age refer to? Maybe the current epoch?

The age of the pool. This is what you can use the subquery data for, so you can use pools.createdAt  from the subquery to calculate how long the pool has existed.

> 3. Average asset maturity: where does this number come from or how can it be calculated?

This is a bit tricky:
You need to get the list of assets/loans, I think there’s a hook for that already since we are showing the list on the pool detail page I think.
Then you need to filter these loans to only ongoing loans (debt > 0 ).
Then you need to filter these loans to exclude CreditLine loan type loans (these don’t have a maturity date).
And now finally, you need to calculate the actual average maturity. Maturity term is maturity date - origination date, and then you need to take the average of this across the filtered loans, weighted by the debt. We’re also doing this in Tinlake UI, see this: https://github.com/centrifuge/apps/blob/main/tinlake-ui/containers/Investment/View/InvestmentOverview.tsx#L66
