### ISSUE TITLE
fix altair colour scheme

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#851]
currently the active items (menu, tabs, titles etc.)  are blue (as it should be in the white design)
On Altair it should be Yellow. see [Figma](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=4440%3A100305)

Example AS IS:
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/168e00f2-2f48-47ae-8019-c256a31c6cca)

Example Target:
![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/739ed123-8c5f-4a49-87be-cbaa00ef5e37)

**Comment by armandomistral** [comment]
Issues spotted while testing the dark theme on https://dev.app.cntrfg.com/. Can't take screenshots anymore since all data got cleared, but here's the list:
- **Table**: Background color is dark gray but should be backgroundPage (black)
- **Investment component**: Background color is dark gray but should be backgroundPage
- **Tooltip indicator**: Color is white but should be the label color (textSecondary)
