### ISSUE TITLE
Tokens on pool details  [Must have]

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#857]
## Background
We want to no longer have the token detail "separate" from the pool. So instead of a table in the pool details, we want the token summary with a call to action to invest. Including the token detail in the pool prevents users from switching between token details of the same pools, and allows them to compare the pool tokens in place.

As of NOW there is no graph yet, so there is no need for the "foldout" (i.e. expanding the card). Once the graph data is available, we'll make a new ticket to add the token-specific graph inside the foldout. 

## Acceptance criteria
* The token detail information is available in the pool detail's Overview tab
* A user can invest in the tokens of the pool
* The investment component is shown regardless of the selected tab (Overview, Assets, Liquidity)

## Behavior
* Token cards are listed by descending seniority
* The `Invest` button of the most senior token is marked as primary button
* Clicking `Invest` in a token card selects the token in the investment component and sets the amount input field in focus (most senior token is default option, symmetrical to the primary button)
* The token symbol of the selected token is appended to the label of the submit button of the investment component (e.g. `FOOSEN`)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/b16a1a17-b632-47d0-8d6f-751eaab3704f)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/29b1f736-3425-4a41-9963-d97b1960ec07)

### Note on the target behavior (future version)
Once token cards are expandable to show the price & yield chart, the envisioned behavior will respond to whether a token got selected on the token menu:
* When a user enters the pool detail from the pool menu:
   * The `Invest` action in the card of the most senior token is marked as the primary button (in yellow)
   * The most senior token is selected in the investment component
* When a user enters the pool detail from the token menu:
   * The `Invest` action in the card of the selected token is marked as the primary button
   * The clicked token is selected in the investment component

#### Case 1 - Not whitelisted, not invested
* The Pool terms are shown in the toolbar
* Action: `Invest` on token card opens onboarding flow

#### Case 2 - Whitelisted, not invested
* If whitelisted, the `Invest` button in the token card shows the circle icon as action qualifier.
* Action: `Invest` selects token in dropdown and sets amount input into focus

#### Case 3 - Whitelisted, invested (Invest more)
* If invested, the `Invest` button in the token card shows the checkmark icon as action qualifier.
* Action: `Invest` (and `Invest more`) displays investment form and sets amount input into focus
* Action: `Redeem` displays redemption form and sets amount input into focus

#### Case 4 - Whitelisted, invested (Invest in another token)
* If not whitelisted: `Invest` opens _Onboarding to token_
* If whitelisted: `Invest` opens new token investment form

## Mockups
* [Pool detail > Overview (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=921%3A14665)
* [Investment component: First & subsequent investment](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=1682%3A69344)
* [Token investment life cycle (Figma)](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=5820%3A112065)

**Comment by EstherCentrifuge** [comment]
I like it  a lot! but lest have @armandomistral look at it for ui feedback

**Comment by armandomistral** [comment]
Ok, @EstherCentrifuge, I've tested the version https://dev.app.altair.cntrfg.com/investments. Here are the things which do not match with the specification and hence should be added and improved. I'm aware this ticket got created for Centrifuge App, but it the issues below should be fixed to work on Altair.

### Case: Not whitelisted, not invested
The buttons are enabled, and no investment component is shown.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/23652850/180780247-4217a3fb-0b9b-49c8-8c20-1d3276e14d2c.png">
Clicking `Invest` show the message `Not allowed to invest`, but no action to request a whitelisting is provided.
<img width="291" alt="image" src="https://user-images.githubusercontent.com/23652850/180780471-3302d73d-3f2b-4ede-b326-40e33770b968.png">

**Target**: Offer an action to request getting whitelisted by the Issuer. e.g. a mailto link saying "Contact issuer".

### Toolbar
The investment component is shown only on the _Overview tab_.
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/23652850/180778324-0489fb0b-1bd2-4dad-b28e-59e254f2c065.png">

* **Target**: Show the investment component on every tab (i.e. Overview, Assets, Liquidity), since tokens are global to a pool.

### Token card
* The token thumbnail shows `SEN`, regardless of the seniority, and the token symbol set.
* The Token symbol is missing
<img width="657" alt="image" src="https://user-images.githubusercontent.com/23652850/180778244-2cbfc03c-253c-4ccf-97ab-f7d7412ff65b.png">

* **Target**:
  * Display the token symbol in the token thumbnail, so that it matches the abbreviation in the investment component. Token symbols can wrap to a max. of two lines. Like in the Fabric component https://centrifuge-fabric.netlify.app/?path=/story/components-thumbnail--default&args=label:BLIJUN;size:small
  * Display the token symbol next to the token name

The capacity is shown in green status color if the capacity is 0.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/23652850/180779030-26235e24-5d7d-4f3c-b6bf-12129a358342.png">

**Target**: Apply the color `Status:warning` if the token capacity <=0

**Comment by armandomistral** [comment]
Thanks, @onnovisser & @sophialittlejohn!! I've tested https://dev.app.altair.cntrfg.com/investments/4185558569:
* Target: If an address is not whitelisted to a token: ✅
  * The Invest button in the token card is disabled
  * The investment component in the toolbar shows the message Not allowed to invest (no action to request whitelisting is provided since this is not desired for Pool on Altair.)
  <img width="1055" alt="image" src="https://user-images.githubusercontent.com/23652850/181279295-d6efa4f6-1642-47b4-96c1-fe4eab7afec5.png">
* Target: Show the investment component on every tab (i.e. Overview, Assets, Liquidity), since tokens are global to a pool: ✅
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/23652850/181279799-ee576182-e0e5-4141-8221-31b39217da31.png">
* Target: Display the token symbol in the token thumbnail, so that it matches the abbreviation in the investment component. ✅
<img width="670" alt="image" src="https://user-images.githubusercontent.com/23652850/181280513-38e06fd0-8793-4850-832e-e7607e2ebcc0.png">
* Target: Apply the color Status:warning if the token capacity <=0: ✅
* Target: Display the token symbol next to the token name: ⚠️
![image](https://user-images.githubusercontent.com/23652850/181280668-954aed6b-6fd2-43bd-a9bb-d82e97f2211b.png)
The token symbol (e.g. `BLIJUN`) is missing. See [component](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1-(Master)?node-id=5605%3A99098). But this does not block the release.
