### ISSUE TITLE
Asset list update Altair release

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#885]
After discussion we agreed on a few changes:

### **1. Fixed "Financing date" instead of dynamic maturity** 
* We will show financing date (FIRST!) -> remove the updating maturity
* Please change the label from `Maturity` to `Financing date`

### **2. Amount in the asset list should display the outstanding amount** 
*  Please also update the label to `Outstanding`
* [Asset list (Figma)](https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=4375%3A167720)

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/811e5150-cfa3-42dc-8ee8-51bbed5f9ee2)

**Comment by sophialittlejohn** [comment]
##  ~Maturity~ Financing date

The date will be visible in this column if
1. the loan is "active"
2. an origination date is set (this only happens when the asset has been priced and is therefore active)
3. the asset has been (partially) financed `totalBorrowed != 0`
4. the interest rate is not zero

##  ~Amount~ Outstanding
value is hidden if the loan has not been priced yet - without pricing there can be no financing 🤷‍♀️ 

Please let me know if I should change anything

**Comment by armandomistral** [comment]
@sophialittlejohn & @EstherCentrifuge, I think we could hide the outstanding amount in the `Outstanding` column when depending on whether it's relevant for the status. For `Credit line with maturity` assets, this could be:
* **Created**: Not shown
* **Priced**: Not shown
* **Ongoing**: Shown
* **Repaid**: Shown (should be 0)
* **Closed**: Not shown
See https://www.figma.com/file/LCbVWH8fXPkXMbLpC3VZtx/Centrifuge-app---Altair?node-id=6804%3A34602. WDYT?

**Comment by sophialittlejohn** [comment]
@armandomistral I think that works 👍 

for me this means only show when loan status  
`Active && Closed --> outstandingDebt === 0`

**Comment by EstherCentrifuge** [comment]
Also it's already like this but just to confirm the ordering should be by Asset number
