### ISSUE TITLE
upgrade: Dissable financing after maturity date

### ISSUE THREAD

**Issue by EstherCentrifuge** [centrifuge/apps#896]
AS IS. 
When trying to finance an asset after the maturity date the transaction fails due to the maturity date being in the past.
This is great! and a logic we want. but it would be nicer if we can dissable the button to finance completly as it sames a try to transaction. 

![image.png](https://images.zenhubusercontent.com/61fa54b8b520bc58fd924e32/003fa2df-6fcb-4dc7-86d8-7413aac86415)

**Comment by armandomistral** [comment]
Ok, @onnovisser & @EstherCentrifuge, I've tested the case of "Financing after passed maturity date" on https://dev.app.cntrfg.com/investments/1540118755/assets/3. I think it works, because the Finance form is hidden – only `Close` is available. I think this can be moved to "Ready"...
![image.png](https://images.zenhubusercontent.com/6090f1ca0d0c23544195c7ec/b25adc2b-8abd-4177-8f10-af9616609665)
